// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The inputs, outputs, and detailed explanation of the Autoscaling
/// recommendation.
public struct AutoscalerRecommendation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The autoscaling algorithm inputs.
  public var inputs: AutoscalerRecommendation.Inputs? = nil

  /// The algorithm outputs for the recommended cluster size.
  public var outputs: AutoscalerRecommendation.Outputs? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AutoscalerRecommendation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoscalerRecommendation().with { $0.inputs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputs = CodingKeys(stringValue: "inputs")
    static let outputs = CodingKeys(stringValue: "outputs")

    static let _knownKeys: Set<Swift.String> = [
      "inputs",
      "outputs",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.inputs = try container.decodeIfPresent(
      AutoscalerRecommendation.Inputs.self, forKey: .inputs)
    self.outputs = try container.decodeIfPresent(
      AutoscalerRecommendation.Outputs.self, forKey: .outputs)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.inputs, forKey: .inputs)
    try container.encodeIfPresent(self.outputs, forKey: .outputs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The input values for the Autoscaling recommendation algorithm.
  public struct Inputs: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The metrics collected by the Dataproc agent running on the cluster.
    /// For example, {"avg-yarn-pending-memory": "1040 MB"}
    public var clusterMetrics: [Swift.String: Swift.String] = [:]

    /// The cluster configuration before updating the cluster.
    public var currentClusterSize: ClusterSize? = nil

    /// The minimum worker counts for each instance group.
    public var minWorkerCounts: ClusterSize? = nil

    /// The maximum worker counts for each instance group.
    public var maxWorkerCounts: ClusterSize? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Inputs`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Inputs().with { $0.clusterMetrics = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clusterMetrics = CodingKeys(stringValue: "clusterMetrics")
      static let currentClusterSize = CodingKeys(stringValue: "currentClusterSize")
      static let minWorkerCounts = CodingKeys(stringValue: "minWorkerCounts")
      static let maxWorkerCounts = CodingKeys(stringValue: "maxWorkerCounts")

      static let _knownKeys: Set<Swift.String> = [
        "clusterMetrics",
        "currentClusterSize",
        "minWorkerCounts",
        "maxWorkerCounts",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .clusterMetrics)
      {
        self.clusterMetrics = value
      }
      self.currentClusterSize = try container.decodeIfPresent(
        ClusterSize.self, forKey: .currentClusterSize)
      self.minWorkerCounts = try container.decodeIfPresent(
        ClusterSize.self, forKey: .minWorkerCounts)
      self.maxWorkerCounts = try container.decodeIfPresent(
        ClusterSize.self, forKey: .maxWorkerCounts)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clusterMetrics, forKey: .clusterMetrics)
      try container.encodeIfPresent(self.currentClusterSize, forKey: .currentClusterSize)
      try container.encodeIfPresent(self.minWorkerCounts, forKey: .minWorkerCounts)
      try container.encodeIfPresent(self.maxWorkerCounts, forKey: .maxWorkerCounts)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.logging.AutoscalerRecommendation.Inputs"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Autoscaler recommendations.
  public struct Outputs: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The high-level autoscaling decision, such as SCALE_UP, SCALE_DOWN,
    /// NO_OP.
    public var decision: ScalingDecisionType = ScalingDecisionType()

    /// The recommended cluster size.
    public var recommendedClusterSize: ClusterSize? = nil

    /// The graceful decommission timeout for downscaling operations.
    public var gracefulDecommissionTimeout: GoogleCloudWKT.Duration? = nil

    /// Reasons why the Autoscaler didn't add or remove more workers.
    public var constraintsReached: [ConstrainingFactor] = []

    /// Less significant recommendations that are not included in the
    /// `AutoscalerStatus.details` message.
    public var additionalRecommendationDetails: [Swift.String] = []

    /// A unique id for this recommendation that should be included when opening
    /// a support ticket.
    public var recommendationId: Swift.String = Swift.String()

    /// The metric source deciding the autoscaling recommendation.
    public var decisionMetric: MetricType = MetricType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Outputs`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Outputs().with { $0.decision = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let decision = CodingKeys(stringValue: "decision")
      static let recommendedClusterSize = CodingKeys(stringValue: "recommendedClusterSize")
      static let gracefulDecommissionTimeout = CodingKeys(
        stringValue: "gracefulDecommissionTimeout")
      static let constraintsReached = CodingKeys(stringValue: "constraintsReached")
      static let additionalRecommendationDetails = CodingKeys(
        stringValue: "additionalRecommendationDetails")
      static let recommendationId = CodingKeys(stringValue: "recommendationId")
      static let decisionMetric = CodingKeys(stringValue: "decisionMetric")

      static let _knownKeys: Set<Swift.String> = [
        "decision",
        "recommendedClusterSize",
        "gracefulDecommissionTimeout",
        "constraintsReached",
        "additionalRecommendationDetails",
        "recommendationId",
        "decisionMetric",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(ScalingDecisionType.self, forKey: .decision) {
        self.decision = value
      }
      self.recommendedClusterSize = try container.decodeIfPresent(
        ClusterSize.self, forKey: .recommendedClusterSize)
      self.gracefulDecommissionTimeout = try container.decodeIfPresent(
        GoogleCloudWKT.Duration.self, forKey: .gracefulDecommissionTimeout)
      if let value = try container.decodeIfPresent(
        [ConstrainingFactor].self, forKey: .constraintsReached)
      {
        self.constraintsReached = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .additionalRecommendationDetails)
      {
        self.additionalRecommendationDetails = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recommendationId) {
        self.recommendationId = value
      }
      if let value = try container.decodeIfPresent(MetricType.self, forKey: .decisionMetric) {
        self.decisionMetric = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.decision, forKey: .decision)
      try container.encodeIfPresent(self.recommendedClusterSize, forKey: .recommendedClusterSize)
      try container.encodeIfPresent(
        self.gracefulDecommissionTimeout, forKey: .gracefulDecommissionTimeout)
      try container.encode(self.constraintsReached, forKey: .constraintsReached)
      try container.encode(
        self.additionalRecommendationDetails, forKey: .additionalRecommendationDetails)
      try container.encode(self.recommendationId, forKey: .recommendationId)
      try container.encode(self.decisionMetric, forKey: .decisionMetric)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.logging.AutoscalerRecommendation.Outputs"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.logging.AutoscalerRecommendation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
