// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The Autoscaler state.
public enum AutoscalerState: Codable, Equatable, Sendable {
  case unspecified
  /// The Autoscaler is sleeping and waiting for the next update.
  case cooldown
  /// The Autoscaler is scaling the cluster.
  case scaling
  /// The Autoscaler has stopped.
  case stopped
  /// The Autoscaler has failed.
  case failed
  /// The Autoscaler is initializing.
  case initializing
  /// The Autoscaler is in the process of calculating its recommendation on
  /// whether to scale the cluster, and if so, how to autoscale.
  case recommending
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .cooldown: return 1
    case .scaling: return 2
    case .stopped: return 3
    case .failed: return 4
    case .initializing: return 5
    case .recommending: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "AUTOSCALER_STATE_UNSPECIFIED"
    case .cooldown: return "COOLDOWN"
    case .scaling: return "SCALING"
    case .stopped: return "STOPPED"
    case .failed: return "FAILED"
    case .initializing: return "INITIALIZING"
    case .recommending: return "RECOMMENDING"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AutoscalerState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "AUTOSCALER_STATE_UNSPECIFIED": self = .unspecified
    case "COOLDOWN": self = .cooldown
    case "RECOMMENDING": self = .recommending
    case "SCALING": self = .scaling
    case "STOPPED": self = .stopped
    case "FAILED": self = .failed
    case "INITIALIZING": self = .initializing
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AutoscalerState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .cooldown
    case 2: self = .scaling
    case 3: self = .stopped
    case 4: self = .failed
    case 5: self = .initializing
    case 6: self = .recommending
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .cooldown: return try container.encode(1)
    case .scaling: return try container.encode(2)
    case .stopped: return try container.encode(3)
    case .failed: return try container.encode(4)
    case .initializing: return try container.encode(5)
    case .recommending: return try container.encode(6)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
