// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

public enum ConstrainingFactor: Codable, Equatable, Sendable {
  case unspecified
  /// The project does not have sufficient regional, global, and or preemptible
  /// quota to allocate a new VM.
  case scalingCappedDueToLackOfQuota
  /// All worker groups have reached maximum size. This message will not be
  /// issued if one group reached maximum size, but workers were able to be
  /// allocated to another group.
  case reachedMaximumClusterSize
  /// All worker groups have reached minimum size. This message will not be
  /// issued if workers were able to be removed from another group that had not
  /// reached minimum size.
  case reachedMinimumClusterSize
  /// The secondary worker group cannot be scaled down by more than 1k nodes in a
  /// single update request.
  case secondaryScaledownSingleRequestLimitReached
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .scalingCappedDueToLackOfQuota: return 1
    case .reachedMaximumClusterSize: return 2
    case .reachedMinimumClusterSize: return 3
    case .secondaryScaledownSingleRequestLimitReached: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "CONSTRAINING_FACTOR_UNSPECIFIED"
    case .scalingCappedDueToLackOfQuota: return "SCALING_CAPPED_DUE_TO_LACK_OF_QUOTA"
    case .reachedMaximumClusterSize: return "REACHED_MAXIMUM_CLUSTER_SIZE"
    case .reachedMinimumClusterSize: return "REACHED_MINIMUM_CLUSTER_SIZE"
    case .secondaryScaledownSingleRequestLimitReached:
      return "SECONDARY_SCALEDOWN_SINGLE_REQUEST_LIMIT_REACHED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConstrainingFactor/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "CONSTRAINING_FACTOR_UNSPECIFIED": self = .unspecified
    case "SCALING_CAPPED_DUE_TO_LACK_OF_QUOTA": self = .scalingCappedDueToLackOfQuota
    case "REACHED_MAXIMUM_CLUSTER_SIZE": self = .reachedMaximumClusterSize
    case "REACHED_MINIMUM_CLUSTER_SIZE": self = .reachedMinimumClusterSize
    case "SECONDARY_SCALEDOWN_SINGLE_REQUEST_LIMIT_REACHED":
      self = .secondaryScaledownSingleRequestLimitReached
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConstrainingFactor/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .scalingCappedDueToLackOfQuota
    case 2: self = .reachedMaximumClusterSize
    case 3: self = .reachedMinimumClusterSize
    case 4: self = .secondaryScaledownSingleRequestLimitReached
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .scalingCappedDueToLackOfQuota: return try container.encode(1)
    case .reachedMaximumClusterSize: return try container.encode(2)
    case .reachedMinimumClusterSize: return try container.encode(3)
    case .secondaryScaledownSingleRequestLimitReached: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
