// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Reconciliation log for session ttl event.
public struct ReconciliationLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The reconciliation algorithm inputs.
  public var inputs: ReconciliationLog.Inputs? = nil

  /// The algorithm outputs for the recommended reconciliation operation.
  public var outputs: ReconciliationLog.Outputs? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReconciliationLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReconciliationLog().with { $0.inputs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputs = CodingKeys(stringValue: "inputs")
    static let outputs = CodingKeys(stringValue: "outputs")

    static let _knownKeys: Set<Swift.String> = [
      "inputs",
      "outputs",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.inputs = try container.decodeIfPresent(ReconciliationLog.Inputs.self, forKey: .inputs)
    self.outputs = try container.decodeIfPresent(ReconciliationLog.Outputs.self, forKey: .outputs)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.inputs, forKey: .inputs)
    try container.encodeIfPresent(self.outputs, forKey: .outputs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The input values for the Reconciler recommendation algorithm.
  /// We could add more details in future if required.
  public struct Inputs: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Idle duration
    public var idleDuration: GoogleWKT.Duration? = nil

    /// Configured idle TTL
    public var idleTtl: GoogleWKT.Duration? = nil

    /// Total session lifetime
    public var sessionLifetime: GoogleWKT.Duration? = nil

    /// Configured ttl
    public var ttl: GoogleWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Inputs`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Inputs().with { $0.idleDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let idleDuration = CodingKeys(stringValue: "idleDuration")
      static let idleTtl = CodingKeys(stringValue: "idleTtl")
      static let sessionLifetime = CodingKeys(stringValue: "sessionLifetime")
      static let ttl = CodingKeys(stringValue: "ttl")

      static let _knownKeys: Set<Swift.String> = [
        "idleDuration",
        "idleTtl",
        "sessionLifetime",
        "ttl",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.idleDuration = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .idleDuration)
      self.idleTtl = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .idleTtl)
      self.sessionLifetime = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .sessionLifetime)
      self.ttl = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .ttl)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.idleDuration, forKey: .idleDuration)
      try container.encodeIfPresent(self.idleTtl, forKey: .idleTtl)
      try container.encodeIfPresent(self.sessionLifetime, forKey: .sessionLifetime)
      try container.encodeIfPresent(self.ttl, forKey: .ttl)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.logging.ReconciliationLog.Inputs"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Reconciler recommendations.
  public struct Outputs: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The high-level reconciliation decision.
    public var decision: ReconciliationDecisionType = ReconciliationDecisionType()

    /// Human readable context messages which explain the reconciler decision.
    public var decisionDetails: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Outputs`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Outputs().with { $0.decision = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let decision = CodingKeys(stringValue: "decision")
      static let decisionDetails = CodingKeys(stringValue: "decisionDetails")

      static let _knownKeys: Set<Swift.String> = [
        "decision",
        "decisionDetails",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        ReconciliationDecisionType.self, forKey: .decision)
      {
        self.decision = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .decisionDetails) {
        self.decisionDetails = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.decision, forKey: .decision)
      try container.encode(self.decisionDetails, forKey: .decisionDetails)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.logging.ReconciliationLog.Outputs"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.logging.ReconciliationLog"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
