// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Reconciliation log for session ttl event.
public struct ReconciliationLog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The reconciliation algorithm inputs.
  public var inputs: ReconciliationLog.Inputs? = nil

  /// The algorithm outputs for the recommended reconciliation operation.
  public var outputs: ReconciliationLog.Outputs? = nil

  /// Initialize a new instance of `ReconciliationLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReconciliationLog().with { $0.inputs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The input values for the Reconciler recommendation algorithm.
  /// We could add more details in future if required.
  public struct Inputs: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Idle duration
    public var idleDuration: GoogleCloudWkt.Duration? = nil

    /// Configured idle TTL
    public var idleTtl: GoogleCloudWkt.Duration? = nil

    /// Total session lifetime
    public var sessionLifetime: GoogleCloudWkt.Duration? = nil

    /// Configured ttl
    public var ttl: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `Inputs`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Inputs().with { $0.idleDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.logging.ReconciliationLog.Inputs"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Reconciler recommendations.
  public struct Outputs: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The high-level reconciliation decision.
    public var decision: ReconciliationDecisionType = ReconciliationDecisionType()

    /// Human readable context messages which explain the reconciler decision.
    public var decisionDetails: Swift.String = Swift.String()

    /// Initialize a new instance of `Outputs`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Outputs().with { $0.decision = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.logging.ReconciliationLog.Outputs"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.logging.ReconciliationLog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
