// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The Autoscaling decision type.
public enum ScalingDecisionType: Codable, Equatable, Sendable {
  case unspecified
  /// Increase the number of primary and/or secondary workers.
  case scaleUp
  /// Decrease the number of primary and/or secondary workers.
  case scaleDown
  /// Not changing the number of primary or secondary workers.
  case noScale
  /// Scale the primary and secondary worker groups in different directions.
  case mixed
  /// Cancel the ongoing scale down operation.
  case cancel
  /// Do not cancel the ongoing scale down operation.
  case doNotCancel
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .scaleUp: return 1
    case .scaleDown: return 2
    case .noScale: return 3
    case .mixed: return 4
    case .cancel: return 5
    case .doNotCancel: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "SCALING_DECISION_TYPE_UNSPECIFIED"
    case .scaleUp: return "SCALE_UP"
    case .scaleDown: return "SCALE_DOWN"
    case .noScale: return "NO_SCALE"
    case .mixed: return "MIXED"
    case .cancel: return "CANCEL"
    case .doNotCancel: return "DO_NOT_CANCEL"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ScalingDecisionType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "SCALING_DECISION_TYPE_UNSPECIFIED": self = .unspecified
    case "SCALE_UP": self = .scaleUp
    case "SCALE_DOWN": self = .scaleDown
    case "NO_SCALE": self = .noScale
    case "MIXED": self = .mixed
    case "CANCEL": self = .cancel
    case "DO_NOT_CANCEL": self = .doNotCancel
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ScalingDecisionType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .scaleUp
    case 2: self = .scaleDown
    case 3: self = .noScale
    case 4: self = .mixed
    case 5: self = .cancel
    case 6: self = .doNotCancel
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .scaleUp: return try container.encode(1)
    case .scaleDown: return try container.encode(2)
    case .noScale: return try container.encode(3)
    case .mixed: return try container.encode(4)
    case .cancel: return try container.encode(5)
    case .doNotCancel: return try container.encode(6)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
